# Built with Jekyll 3.2.0

# Setup
title:               Janet Ruppert
tagline:             'PhD Candidate in Information Science at CU Boulder'
description:         'PhD Candidate in Information Science at CU Boulder'
url:                 'localhost:4000'
baseurl:             '/ed'

# About/contact
author:
  name:              Janet Ruppert
  url:               https://www.linkedin.com/in/janet-ruppert-1bb7a1225
  email:             janet.ruppert@colorado.edu
  twitter_username:  astrojanet

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


